### ISSUE TITLE
Update windows case to the document

### ISSUE THREAD

**Issue by junaruga** [team-gogut/yamp-arm#18]
As @ZZhangchen is succeeded to install "yamp-arm" and he has something to add to the document, I ask you to contribute it to this repository by "pull-request".

Here is the detail and how to send pull-request.
https://github.com/team-gogut/yamp-arm/commit/9f5bd109db98ee99e15478cf9df5204d1f91871f

And the reference he sent me is https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly

Thanks!

**Comment by ZZhangchen** [comment]
Hi Jun, is it because I used `-f` to push the commit therefore it closed the request?

**Comment by junaruga** [comment]
> Hi Jun, is it because I used -f to push the commit therefore it closed the request?

No, I do not think so. There are 2 commands to delete the remote repository's branch.

https://stackoverflow.com/questions/2003505/how-do-i-delete-a-git-branch-locally-and-remotely

```
$ git push <remote_name> --delete <branch_name>
```

```
$ git push <remote_name> :<branch_name>
```

`git push ZZhangchen <branch name> -f` is just only to override ZZhangchen repository's branch by your local repository's same name's branch.

**Comment by junaruga** [comment]
Fixed by https://github.com/team-gogut/yamp-arm/pull/20 .
